language: ruby
matrix:
  allow_failures:
    - rvm: jruby-9.2.8.0
      gemfile: gemfiles/rails_60.gemfile
  include:
    - rvm: 2.2.10
    - rvm: 2.3.8
    - rvm: 2.5.5
    - rvm: 2.6.3

script: bundle exec rake test
